[package]
name = "http-server-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
fs-err = "2.11.0"
log = "0.4.21"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
toml = "0.8.14"
